version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: springboot-postgres
    environment:
      POSTGRES_DB: intern_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/intern_db
      JDBC_USERNAME: postgres
      JDBC_PASSWORD: mysecretpassword
      SERVER_PORT: 8082

volumes:
  postgres_data:
